# Generated by Django 5.1.4 on 2026-02-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(primary_key=True, serialize=False)),
                ('titre_evenement', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('type_evenement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('tel', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('id_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.utilisateur')),
            ],
        ),
    ]
