# Generated by Django 5.1.4 on 2026-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='statut',
            field=models.CharField(default='actif', max_length=50),
        ),
    ]
