# Generated by Django 5.1.4 on 2026-02-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_administrateur_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='statut',
            new_name='status',
        ),
    ]
