# Generated by Django 5.1.4 on 2026-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_statut_administrateur_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
