# Generated by Django 5.1.4 on 2026-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_statut_administrateur_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='est_utilise',
            field=models.BooleanField(default=False),
        ),
    ]
