# Generated by Django 5.1.4 on 2026-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
