# Generated by Django 6.0.2 on 2026-02-09 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_achat_est_utilise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id_favori', models.AutoField(primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_utilisateurs', to='tickets.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='tickets.utilisateur')),
            ],
            options={
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'evenement')},
            },
        ),
    ]
