# Generated by Django 6.0.2 on 2026-02-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tickets.evenement')),
            ],
            options={
                'ordering': ['date_heure'],
                'unique_together': {('evenement', 'date_heure')},
            },
        ),
        migrations.AddField(
            model_name='achat',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='tickets.session'),
        ),
    ]
