# Generated by Django 5.1.4 on 2026-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='administrateurs/'),
        ),
    ]
