# Generated by Django 6.0.2 on 2026-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_session_achat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
