# Generated by Django 6.0.2 on 2026-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_evenement_latitude_evenement_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='interests',
            field=models.TextField(blank=True, default='', help_text='Comma-separated interests (e.g., Music,Tech,Art)'),
        ),
    ]
