# Generated by Django 5.1.4 on 2026-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_administrateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='code_qr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_parrainage',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='total_code_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
