# Generated by Django 5.1.4 on 2026-02-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_achat_code_qr_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
