# Generated by Django 6.0.2 on 2026-02-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_utilisateur_interests'),
        ('tickets', '0009_alter_utilisateur_last_login'),
    ]

    operations = [
    ]
