# Generated by Django 5.1.4 on 2026-02-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_merge_20260210_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('achat', 'Achat de ticket'), ('bonus_parrainage', 'Bonus parrainage')], max_length=50)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('especes', 'Espèces')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description ou note sur la transaction', null=True)),
                ('id_achat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='tickets.achat')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tickets.utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
