# Generated by Django 5.1.4 on 2026-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='date_utilisation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation du ticket', null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='Image PNG du QR code', null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='code_qr',
            field=models.CharField(blank=True, help_text='Code unique UUID pour le QR', max_length=255, null=True, unique=True),
        ),
    ]
