# Generated by Django 5.1.4 on 2026-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_achat_date_utilisation_achat_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
